# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    set ::env(RT_TMP) "./.Xil/Vivado-26778-com1549.eecs.utk.edu/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a100tcsg324-1

    source $::env(SYNTH_COMMON)/common_vhdl.tcl
    set rt::defaultWorkLibName xil_defaultlib

    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include {
    /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog
    /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog
    /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog
  } {
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_all_typeA.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_all_typeA_slice.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_allx_typeA.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_allx_typeA_nodelay.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_async_edge_transfer.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_bscan.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_bufr.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut4.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut5.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut6.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut7.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_cfglut8.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_generic_memory_read.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_generic_mux.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_match.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_match_nodelay.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_rising_edge_detection.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_startup.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_general_components_lib_v2_0/hdl/verilog/cs_async_transfer.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_register_stat.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_register_p2s.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_register.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_register_ctl.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_register_stream.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_xsdb_interface_buffers.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/labtools_xsdb_slave_lib_v3_0/hdl/verilog/labtools_xsdb_slave_lib_v3_0_chipscope_xsdb_slave.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_cap_addrgen.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_cap_ctrl_legacy.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_cap_sample_counter.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_cap_window_counter.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_core.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_register.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_reset_ctrl.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_trace_memory.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_trig_match.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_adv_trigger_sequencer.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_counter.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_counter_match.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_fsm_memory_read.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila_trigger.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/ila_v4_0/hdl/verilog/ila_v4_0_ila.v
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/synth/u_ila_0_CV.v
    }
      rt::read_vhdl -lib blk_mem_gen_v8_1 {
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_v8_1_synth_comp.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_v8_1_defaults.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_v8_1_pkg.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_getinit_pkg.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_min_area_pkg.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_bindec.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_mux.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_prim_wrapper.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_prim_wrapper_init.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_prim_width.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_generic_cstr.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_ecc_encoder.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_ecc_decoder.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_input_block.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_output_block.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_axi_read_fsm.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_axi_read_wrapper.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_axi_write_fsm.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_axi_write_wrapper.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_axi_regs_fwd.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_top.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_v8_1_synth.vhd
      /data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.cache/7e2aaccf/.tmp/.srcs/sources_1/ip/u_ila_0_CV/blk_mem_gen_v8_1/blk_mem_gen_v8_1.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top u_ila_0_CV
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-26778-com1549.eecs.utk.edu/"
    if {$rt::useElabCache == false} {
      rt::run_rtlelab -module $rt::top
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    if { $rt::flowresult == 1 } { return -code error }

    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
    }


    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  return -code "error" $rt::result
}
