# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/mult_gen_0/mult_gen_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/mult_gen_0/mult_gen_0_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

read_ip /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/c_addsub_0/c_addsub_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/c_addsub_0/c_addsub_0_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/c_addsub_0/c_addsub_0.xci]

read_ip /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/cordic_0/cordic_0.xci
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/cordic_0/cordic_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/cordic_0/cordic_0.dcp]
set_property used_in_implementation false [get_files -all /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/cordic_0/cordic_0_ooc.xdc]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/ip/cordic_0/cordic_0.xci]

read_vhdl -library xil_defaultlib {
  /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/imports/chris/magnitude/magnitude.srcs/sources_1/new/magnitude.vhd
  /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/imports/chris/averager/averager.srcs/sources_1/new/averager.vhd
  /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.srcs/sources_1/new/disp_draw.vhd
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /data1/cdaffron/git/ece551hw/final/chris/disp_draw/disp_draw.cache/wt [current_project]
set_property parent.project_dir /data1/cdaffron/git/ece551hw/final/chris/disp_draw [current_project]
catch { write_hwdef -file disp_draw.hwdef }
synth_design -top disp_draw -part xc7a100tcsg324-1
write_checkpoint disp_draw.dcp
report_utilization -file disp_draw_utilization_synth.rpt -pb disp_draw_utilization_synth.pb
