# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/lab2/Nexys4_Master.xdc

# IP: ip/Square_Root/Square_Root.xco
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==Square_Root || ORIG_REF_NAME==Square_Root}]
