set_property SRC_FILE_INFO {cfile:/data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc rfile:../../../top_level_project.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:1132 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:1133 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1134 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1135 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1136 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1137 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1138 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1139 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1140 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:1141 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:1142 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list debug_clk]]
set_property src_info {type:XDC file:1 line:1143 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:1144 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {FFT_addr[0]} {FFT_addr[1]} {FFT_addr[2]} {FFT_addr[3]} {FFT_addr[4]} {FFT_addr[5]} {FFT_addr[6]} {FFT_addr[7]} {FFT_addr[8]} {FFT_addr[9]}]]
set_property src_info {type:XDC file:1 line:1145 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1146 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:1147 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {FFT_data[0]} {FFT_data[1]} {FFT_data[2]} {FFT_data[3]} {FFT_data[4]} {FFT_data[5]} {FFT_data[6]} {FFT_data[7]} {FFT_data[8]} {FFT_data[9]} {FFT_data[10]} {FFT_data[11]} {FFT_data[12]} {FFT_data[13]} {FFT_data[14]} {FFT_data[15]} {FFT_data[16]} {FFT_data[17]} {FFT_data[18]} {FFT_data[19]} {FFT_data[20]} {FFT_data[21]} {FFT_data[22]} {FFT_data[23]} {FFT_data[24]} {FFT_data[25]} {FFT_data[26]} {FFT_data[27]} {FFT_data[28]} {FFT_data[29]} {FFT_data[30]} {FFT_data[31]}]]
set_property src_info {type:XDC file:1 line:1148 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1149 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:1150 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {disp_draw_inst/avg_inst/in0[0]} {disp_draw_inst/avg_inst/in0[1]} {disp_draw_inst/avg_inst/in0[2]} {disp_draw_inst/avg_inst/in0[3]} {disp_draw_inst/avg_inst/in0[4]} {disp_draw_inst/avg_inst/in0[5]} {disp_draw_inst/avg_inst/in0[6]} {disp_draw_inst/avg_inst/in0[7]} {disp_draw_inst/avg_inst/in0[8]} {disp_draw_inst/avg_inst/in0[9]} {disp_draw_inst/avg_inst/in0[10]} {disp_draw_inst/avg_inst/in0[11]} {disp_draw_inst/avg_inst/in0[12]} {disp_draw_inst/avg_inst/in0[13]} {disp_draw_inst/avg_inst/in0[14]} {disp_draw_inst/avg_inst/in0[15]}]]
set_property src_info {type:XDC file:1 line:1151 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1152 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:1153 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {disp_draw_inst/avg_inst/in1[0]} {disp_draw_inst/avg_inst/in1[1]} {disp_draw_inst/avg_inst/in1[2]} {disp_draw_inst/avg_inst/in1[3]} {disp_draw_inst/avg_inst/in1[4]} {disp_draw_inst/avg_inst/in1[5]} {disp_draw_inst/avg_inst/in1[6]} {disp_draw_inst/avg_inst/in1[7]} {disp_draw_inst/avg_inst/in1[8]} {disp_draw_inst/avg_inst/in1[9]} {disp_draw_inst/avg_inst/in1[10]} {disp_draw_inst/avg_inst/in1[11]} {disp_draw_inst/avg_inst/in1[12]} {disp_draw_inst/avg_inst/in1[13]} {disp_draw_inst/avg_inst/in1[14]} {disp_draw_inst/avg_inst/in1[15]}]]
set_property src_info {type:XDC file:1 line:1154 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1155 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:1156 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {disp_draw_inst/avg_inst/in10[0]} {disp_draw_inst/avg_inst/in10[1]} {disp_draw_inst/avg_inst/in10[2]} {disp_draw_inst/avg_inst/in10[3]} {disp_draw_inst/avg_inst/in10[4]} {disp_draw_inst/avg_inst/in10[5]} {disp_draw_inst/avg_inst/in10[6]} {disp_draw_inst/avg_inst/in10[7]} {disp_draw_inst/avg_inst/in10[8]} {disp_draw_inst/avg_inst/in10[9]} {disp_draw_inst/avg_inst/in10[10]} {disp_draw_inst/avg_inst/in10[11]} {disp_draw_inst/avg_inst/in10[12]} {disp_draw_inst/avg_inst/in10[13]} {disp_draw_inst/avg_inst/in10[14]} {disp_draw_inst/avg_inst/in10[15]}]]
set_property src_info {type:XDC file:1 line:1157 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1158 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:1159 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {disp_draw_inst/avg_inst/in11[0]} {disp_draw_inst/avg_inst/in11[1]} {disp_draw_inst/avg_inst/in11[2]} {disp_draw_inst/avg_inst/in11[3]} {disp_draw_inst/avg_inst/in11[4]} {disp_draw_inst/avg_inst/in11[5]} {disp_draw_inst/avg_inst/in11[6]} {disp_draw_inst/avg_inst/in11[7]} {disp_draw_inst/avg_inst/in11[8]} {disp_draw_inst/avg_inst/in11[9]} {disp_draw_inst/avg_inst/in11[10]} {disp_draw_inst/avg_inst/in11[11]} {disp_draw_inst/avg_inst/in11[12]} {disp_draw_inst/avg_inst/in11[13]} {disp_draw_inst/avg_inst/in11[14]} {disp_draw_inst/avg_inst/in11[15]}]]
set_property src_info {type:XDC file:1 line:1160 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1161 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:1162 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {disp_draw_inst/avg_inst/in12[0]} {disp_draw_inst/avg_inst/in12[1]} {disp_draw_inst/avg_inst/in12[2]} {disp_draw_inst/avg_inst/in12[3]} {disp_draw_inst/avg_inst/in12[4]} {disp_draw_inst/avg_inst/in12[5]} {disp_draw_inst/avg_inst/in12[6]} {disp_draw_inst/avg_inst/in12[7]} {disp_draw_inst/avg_inst/in12[8]} {disp_draw_inst/avg_inst/in12[9]} {disp_draw_inst/avg_inst/in12[10]} {disp_draw_inst/avg_inst/in12[11]} {disp_draw_inst/avg_inst/in12[12]} {disp_draw_inst/avg_inst/in12[13]} {disp_draw_inst/avg_inst/in12[14]} {disp_draw_inst/avg_inst/in12[15]}]]
set_property src_info {type:XDC file:1 line:1163 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1164 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:1165 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {disp_draw_inst/avg_inst/in13[0]} {disp_draw_inst/avg_inst/in13[1]} {disp_draw_inst/avg_inst/in13[2]} {disp_draw_inst/avg_inst/in13[3]} {disp_draw_inst/avg_inst/in13[4]} {disp_draw_inst/avg_inst/in13[5]} {disp_draw_inst/avg_inst/in13[6]} {disp_draw_inst/avg_inst/in13[7]} {disp_draw_inst/avg_inst/in13[8]} {disp_draw_inst/avg_inst/in13[9]} {disp_draw_inst/avg_inst/in13[10]} {disp_draw_inst/avg_inst/in13[11]} {disp_draw_inst/avg_inst/in13[12]} {disp_draw_inst/avg_inst/in13[13]} {disp_draw_inst/avg_inst/in13[14]} {disp_draw_inst/avg_inst/in13[15]}]]
set_property src_info {type:XDC file:1 line:1166 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1167 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:1168 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {disp_draw_inst/avg_inst/in14[0]} {disp_draw_inst/avg_inst/in14[1]} {disp_draw_inst/avg_inst/in14[2]} {disp_draw_inst/avg_inst/in14[3]} {disp_draw_inst/avg_inst/in14[4]} {disp_draw_inst/avg_inst/in14[5]} {disp_draw_inst/avg_inst/in14[6]} {disp_draw_inst/avg_inst/in14[7]} {disp_draw_inst/avg_inst/in14[8]} {disp_draw_inst/avg_inst/in14[9]} {disp_draw_inst/avg_inst/in14[10]} {disp_draw_inst/avg_inst/in14[11]} {disp_draw_inst/avg_inst/in14[12]} {disp_draw_inst/avg_inst/in14[13]} {disp_draw_inst/avg_inst/in14[14]} {disp_draw_inst/avg_inst/in14[15]}]]
set_property src_info {type:XDC file:1 line:1169 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1170 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:1171 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {disp_draw_inst/avg_inst/in15[0]} {disp_draw_inst/avg_inst/in15[1]} {disp_draw_inst/avg_inst/in15[2]} {disp_draw_inst/avg_inst/in15[3]} {disp_draw_inst/avg_inst/in15[4]} {disp_draw_inst/avg_inst/in15[5]} {disp_draw_inst/avg_inst/in15[6]} {disp_draw_inst/avg_inst/in15[7]} {disp_draw_inst/avg_inst/in15[8]} {disp_draw_inst/avg_inst/in15[9]} {disp_draw_inst/avg_inst/in15[10]} {disp_draw_inst/avg_inst/in15[11]} {disp_draw_inst/avg_inst/in15[12]} {disp_draw_inst/avg_inst/in15[13]} {disp_draw_inst/avg_inst/in15[14]} {disp_draw_inst/avg_inst/in15[15]}]]
set_property src_info {type:XDC file:1 line:1172 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1173 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:1174 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {disp_draw_inst/avg_inst/in16[0]} {disp_draw_inst/avg_inst/in16[1]} {disp_draw_inst/avg_inst/in16[2]} {disp_draw_inst/avg_inst/in16[3]} {disp_draw_inst/avg_inst/in16[4]} {disp_draw_inst/avg_inst/in16[5]} {disp_draw_inst/avg_inst/in16[6]} {disp_draw_inst/avg_inst/in16[7]} {disp_draw_inst/avg_inst/in16[8]} {disp_draw_inst/avg_inst/in16[9]} {disp_draw_inst/avg_inst/in16[10]} {disp_draw_inst/avg_inst/in16[11]} {disp_draw_inst/avg_inst/in16[12]} {disp_draw_inst/avg_inst/in16[13]} {disp_draw_inst/avg_inst/in16[14]} {disp_draw_inst/avg_inst/in16[15]}]]
set_property src_info {type:XDC file:1 line:1175 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1176 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:1177 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {disp_draw_inst/avg_inst/in2[0]} {disp_draw_inst/avg_inst/in2[1]} {disp_draw_inst/avg_inst/in2[2]} {disp_draw_inst/avg_inst/in2[3]} {disp_draw_inst/avg_inst/in2[4]} {disp_draw_inst/avg_inst/in2[5]} {disp_draw_inst/avg_inst/in2[6]} {disp_draw_inst/avg_inst/in2[7]} {disp_draw_inst/avg_inst/in2[8]} {disp_draw_inst/avg_inst/in2[9]} {disp_draw_inst/avg_inst/in2[10]} {disp_draw_inst/avg_inst/in2[11]} {disp_draw_inst/avg_inst/in2[12]} {disp_draw_inst/avg_inst/in2[13]} {disp_draw_inst/avg_inst/in2[14]} {disp_draw_inst/avg_inst/in2[15]}]]
set_property src_info {type:XDC file:1 line:1178 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1179 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:1180 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {disp_draw_inst/avg_inst/in3[0]} {disp_draw_inst/avg_inst/in3[1]} {disp_draw_inst/avg_inst/in3[2]} {disp_draw_inst/avg_inst/in3[3]} {disp_draw_inst/avg_inst/in3[4]} {disp_draw_inst/avg_inst/in3[5]} {disp_draw_inst/avg_inst/in3[6]} {disp_draw_inst/avg_inst/in3[7]} {disp_draw_inst/avg_inst/in3[8]} {disp_draw_inst/avg_inst/in3[9]} {disp_draw_inst/avg_inst/in3[10]} {disp_draw_inst/avg_inst/in3[11]} {disp_draw_inst/avg_inst/in3[12]} {disp_draw_inst/avg_inst/in3[13]} {disp_draw_inst/avg_inst/in3[14]} {disp_draw_inst/avg_inst/in3[15]}]]
set_property src_info {type:XDC file:1 line:1181 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1182 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:1183 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {disp_draw_inst/avg_inst/in4[0]} {disp_draw_inst/avg_inst/in4[1]} {disp_draw_inst/avg_inst/in4[2]} {disp_draw_inst/avg_inst/in4[3]} {disp_draw_inst/avg_inst/in4[4]} {disp_draw_inst/avg_inst/in4[5]} {disp_draw_inst/avg_inst/in4[6]} {disp_draw_inst/avg_inst/in4[7]} {disp_draw_inst/avg_inst/in4[8]} {disp_draw_inst/avg_inst/in4[9]} {disp_draw_inst/avg_inst/in4[10]} {disp_draw_inst/avg_inst/in4[11]} {disp_draw_inst/avg_inst/in4[12]} {disp_draw_inst/avg_inst/in4[13]} {disp_draw_inst/avg_inst/in4[14]} {disp_draw_inst/avg_inst/in4[15]}]]
set_property src_info {type:XDC file:1 line:1184 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1185 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:1186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {disp_draw_inst/avg_inst/in5[0]} {disp_draw_inst/avg_inst/in5[1]} {disp_draw_inst/avg_inst/in5[2]} {disp_draw_inst/avg_inst/in5[3]} {disp_draw_inst/avg_inst/in5[4]} {disp_draw_inst/avg_inst/in5[5]} {disp_draw_inst/avg_inst/in5[6]} {disp_draw_inst/avg_inst/in5[7]} {disp_draw_inst/avg_inst/in5[8]} {disp_draw_inst/avg_inst/in5[9]} {disp_draw_inst/avg_inst/in5[10]} {disp_draw_inst/avg_inst/in5[11]} {disp_draw_inst/avg_inst/in5[12]} {disp_draw_inst/avg_inst/in5[13]} {disp_draw_inst/avg_inst/in5[14]} {disp_draw_inst/avg_inst/in5[15]}]]
set_property src_info {type:XDC file:1 line:1187 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1188 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:1189 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {disp_draw_inst/avg_inst/in6[0]} {disp_draw_inst/avg_inst/in6[1]} {disp_draw_inst/avg_inst/in6[2]} {disp_draw_inst/avg_inst/in6[3]} {disp_draw_inst/avg_inst/in6[4]} {disp_draw_inst/avg_inst/in6[5]} {disp_draw_inst/avg_inst/in6[6]} {disp_draw_inst/avg_inst/in6[7]} {disp_draw_inst/avg_inst/in6[8]} {disp_draw_inst/avg_inst/in6[9]} {disp_draw_inst/avg_inst/in6[10]} {disp_draw_inst/avg_inst/in6[11]} {disp_draw_inst/avg_inst/in6[12]} {disp_draw_inst/avg_inst/in6[13]} {disp_draw_inst/avg_inst/in6[14]} {disp_draw_inst/avg_inst/in6[15]}]]
set_property src_info {type:XDC file:1 line:1190 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1191 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:1192 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list {disp_draw_inst/avg_inst/in7[0]} {disp_draw_inst/avg_inst/in7[1]} {disp_draw_inst/avg_inst/in7[2]} {disp_draw_inst/avg_inst/in7[3]} {disp_draw_inst/avg_inst/in7[4]} {disp_draw_inst/avg_inst/in7[5]} {disp_draw_inst/avg_inst/in7[6]} {disp_draw_inst/avg_inst/in7[7]} {disp_draw_inst/avg_inst/in7[8]} {disp_draw_inst/avg_inst/in7[9]} {disp_draw_inst/avg_inst/in7[10]} {disp_draw_inst/avg_inst/in7[11]} {disp_draw_inst/avg_inst/in7[12]} {disp_draw_inst/avg_inst/in7[13]} {disp_draw_inst/avg_inst/in7[14]} {disp_draw_inst/avg_inst/in7[15]}]]
set_property src_info {type:XDC file:1 line:1193 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1194 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:1195 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list {disp_draw_inst/avg_inst/in8[0]} {disp_draw_inst/avg_inst/in8[1]} {disp_draw_inst/avg_inst/in8[2]} {disp_draw_inst/avg_inst/in8[3]} {disp_draw_inst/avg_inst/in8[4]} {disp_draw_inst/avg_inst/in8[5]} {disp_draw_inst/avg_inst/in8[6]} {disp_draw_inst/avg_inst/in8[7]} {disp_draw_inst/avg_inst/in8[8]} {disp_draw_inst/avg_inst/in8[9]} {disp_draw_inst/avg_inst/in8[10]} {disp_draw_inst/avg_inst/in8[11]} {disp_draw_inst/avg_inst/in8[12]} {disp_draw_inst/avg_inst/in8[13]} {disp_draw_inst/avg_inst/in8[14]} {disp_draw_inst/avg_inst/in8[15]}]]
set_property src_info {type:XDC file:1 line:1196 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1197 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:1198 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list {disp_draw_inst/avg_inst/in9[0]} {disp_draw_inst/avg_inst/in9[1]} {disp_draw_inst/avg_inst/in9[2]} {disp_draw_inst/avg_inst/in9[3]} {disp_draw_inst/avg_inst/in9[4]} {disp_draw_inst/avg_inst/in9[5]} {disp_draw_inst/avg_inst/in9[6]} {disp_draw_inst/avg_inst/in9[7]} {disp_draw_inst/avg_inst/in9[8]} {disp_draw_inst/avg_inst/in9[9]} {disp_draw_inst/avg_inst/in9[10]} {disp_draw_inst/avg_inst/in9[11]} {disp_draw_inst/avg_inst/in9[12]} {disp_draw_inst/avg_inst/in9[13]} {disp_draw_inst/avg_inst/in9[14]} {disp_draw_inst/avg_inst/in9[15]}]]
set_property src_info {type:XDC file:1 line:1199 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1200 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:1201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list {disp_draw_inst/average[0]} {disp_draw_inst/average[1]} {disp_draw_inst/average[2]} {disp_draw_inst/average[3]} {disp_draw_inst/average[4]} {disp_draw_inst/average[5]} {disp_draw_inst/average[6]} {disp_draw_inst/average[7]} {disp_draw_inst/average[8]} {disp_draw_inst/average[9]} {disp_draw_inst/average[10]} {disp_draw_inst/average[11]} {disp_draw_inst/average[12]} {disp_draw_inst/average[13]} {disp_draw_inst/average[14]} {disp_draw_inst/average[15]}]]
set_property src_info {type:XDC file:1 line:1202 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1203 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:1204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list reset]]
set_property src_info {type:XDC file:1 line:1205 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1206 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:1207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list VGA_trig]]
set_property src_info {type:XDC file:1 line:1208 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1209 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1210 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1211 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets debug_clk]
