# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7a100tcsg324-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.cache/wt [current_project]
set_property parent.project_path /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
add_files {{/mnt/git/Spring-2015/ECE551-Spring-2015/ECE551hw/final/jacob/sources/coe files/gunshot.coe}}
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/c_addsub_0_synth_1/c_addsub_0.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/c_addsub_0_synth_1/c_addsub_0.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/clk_wiz_vga_synth_1/clk_wiz_vga.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/clk_wiz_vga_synth_1/clk_wiz_vga.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/cordic_0_synth_1/cordic_0.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/cordic_0_synth_1/cordic_0.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/mult_gen_0_synth_1/mult_gen_0.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/mult_gen_0_synth_1/mult_gen_0.dcp]
add_files -quiet /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/xfft_0_synth_1/xfft_0.dcp
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.runs/xfft_0_synth_1/xfft_0.dcp]
read_vhdl -library xil_defaultlib {
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/chris/disp_draw/disp_draw.srcs/sources_1/new/type_pkg.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/sources_1/new/vga_pkg.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/new/vga_display_gen.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/vga/vga_controller_640_60.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/new/averager.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/chris/magnitude/magnitude.srcs/sources_1/new/magnitude.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/sources_1/new/vga_top.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/imports/adc_fft_to_pc/adc_fft_fsmV3_noUART.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/new/disp_draw.vhd
  /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/imports/sources_1/new/top_level.vhd
}
read_xdc /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc]

catch { write_hwdef -file top_level.hwdef }
synth_design -top top_level -part xc7a100tcsg324-1 -flatten_hierarchy full
write_checkpoint -noxdef top_level.dcp
catch { report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb }
