# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/mult_gen_0_synth_1/mult_gen_0.dcp
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/mult_gen_0_synth_1/mult_gen_0.dcp]
add_files -quiet /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/cordic_0_synth_1/cordic_0.dcp
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/cordic_0_synth_1/cordic_0.dcp]
add_files -quiet /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/c_addsub_0_synth_1/c_addsub_0.dcp
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.runs/c_addsub_0_synth_1/c_addsub_0.dcp]
read_vhdl -library xil_defaultlib /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.srcs/sources_1/new/magnitude.vhd
read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /data1/cdaffron/git/ece551hw/final/chris/magnitude/magnitude.cache/wt [current_project]
set_property parent.project_dir /data1/cdaffron/git/ece551hw/final/chris/magnitude [current_project]
catch { write_hwdef -file magnitude.hwdef }
synth_design -top magnitude -part xc7a100tcsg324-1
write_checkpoint magnitude.dcp
report_utilization -file magnitude_utilization_synth.rpt -pb magnitude_utilization_synth.pb
