# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp]
read_vhdl -library xil_defaultlib /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.srcs/sources_1/new/pulse_test.vhd
read_xdc /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /data1/cdaffron/git/ece551hw/final/30hz_pulse_test/30hz_pulse_test.cache/wt [current_project]
set_property parent.project_dir /data1/cdaffron/git/ece551hw/final/30hz_pulse_test [current_project]
catch { write_hwdef -file pulse_test.hwdef }
synth_design -top pulse_test -part xc7a100tcsg324-1
write_checkpoint pulse_test.dcp
report_utilization -file pulse_test_utilization_synth.rpt -pb pulse_test_utilization_synth.pb
