# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.cache/wt [current_project]
set_property parent.project_dir /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project [current_project]
catch { write_hwdef -file clk_wiz_vga.hwdef }
synth_design -top clk_wiz_vga -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all clk_wiz_vga_
write_checkpoint -noxdef clk_wiz_vga.dcp
report_utilization -file clk_wiz_vga_utilization_synth.rpt -pb clk_wiz_vga_utilization_synth.pb
if { [catch {
  file copy -force /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.runs/clk_wiz_vga_synth_1/clk_wiz_vga.dcp /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.dcp
  write_verilog -force -mode synth_stub /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_stub.v
  write_vhdl -force -mode synth_stub /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_stub.vhdl
  write_verilog -force -mode funcsim /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_funcsim.v
  write_vhdl -force -mode funcsim /home/jmurra15/classes/ECE551-Spring-2015/ECE551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
