# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files {{Z:/jtobin/matlab/coe files/mat10k.coe}}
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/xfft_0_synth_1/xfft_0.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/xfft_0_synth_1/xfft_0.dcp]
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/ila_1_synth_1/ila_1.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/ila_1_synth_1/ila_1.dcp]
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/vio_1_synth_1/vio_1.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/vio_1_synth_1/vio_1.dcp]
add_files -quiet Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
read_vhdl -library xil_defaultlib {
  Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/imports/sources_1/imports/sources_1/imports/sources_1/imports/sources/uart_tx_generic.vhd
  Z:/jtobin/sources/uart/uart_rx.vhd
  {Z:/jtobin/sources/matlab board control/cmd_decode.vhd}
  Z:/jtobin/sources/adc_fft_to_pc/adc_fft_fsmV3.vhd
  Z:/jtobin/sources/adc_fft_to_pc/topv4.vhd
}
read_xdc Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/constrs_1/imports/sources/Nexys4_audio_id.xdc
set_property used_in_implementation false [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/constrs_1/imports/sources/Nexys4_audio_id.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.cache/wt [current_project]
set_property parent.project_dir Z:/jtobin/vivado_projects/adc_fft_to_pc2 [current_project]
catch { write_hwdef -file topv4.hwdef }
synth_design -top topv4 -part xc7a100tcsg324-1 -fsm_extraction sequential
write_checkpoint topv4.dcp
report_utilization -file topv4_utilization_synth.rpt -pb topv4_utilization_synth.pb
