# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci
# IP: The module: 'clk_wiz_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xci
# IP: The module: 'clk_wiz_vga' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: /mnt/git/Spring-2015/ECE551-Spring-2015/top_level2/top_level2.srcs/sources_1/ip/clk_wiz_vga/clk_wiz_vga_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_vga'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
