# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_vhdl -library xil_defaultlib /data1/cdaffron/git/ece551hw/final/chris/averager/averager.srcs/sources_1/new/averager.vhd
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /data1/cdaffron/git/ece551hw/final/chris/averager/averager.cache/wt [current_project]
set_property parent.project_dir /data1/cdaffron/git/ece551hw/final/chris/averager [current_project]
catch { write_hwdef -file averager.hwdef }
synth_design -top averager -part xc7a100tcsg324-1
write_checkpoint averager.dcp
report_utilization -file averager_utilization_synth.rpt -pb averager_utilization_synth.pb
