# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files -quiet C:/Users/cdaffron/git/ece551/lab2/lab2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/cdaffron/git/ece551/lab2/lab2.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/imports/new/Hex2SSegDecoder.vhd
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/imports/new/HexDigs2SSeg.vhd
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/imports/new/CDiv.vhd
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/imports/lab2/lab2_assem.vhd
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/imports/KCPSM6_Release9_30Sept14/kcpsm6.vhd
  C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/sources_1/new/top_level.vhd
}
read_xdc C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/cdaffron/git/ece551/lab2/lab2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cdaffron/git/ece551/lab2/lab2.cache/wt [current_project]
set_property parent.project_dir C:/Users/cdaffron/git/ece551/lab2 [current_project]
catch { write_hwdef -file top_level.hwdef }
synth_design -top top_level -part xc7a100tcsg324-1
write_checkpoint top_level.dcp
report_utilization -file top_level_utilization_synth.rpt -pb top_level_utilization_synth.pb
