# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xci
# IP: The module: 'vio_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_1'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xci
# IP: The module: 'vio_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
