# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]

read_ip Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xci
set_property used_in_implementation false [get_files z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.dcp]
set_property used_in_implementation false [get_files -all z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.dcp]
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property is_locked true [get_files Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.xci]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.cache/wt [current_project]
set_property parent.project_dir Z:/jtobin/vivado_projects/adc_fft_to_pc2 [current_project]
catch { write_hwdef -file vio_1.hwdef }
synth_design -top vio_1 -part xc7a100tcsg324-1 -mode out_of_context

rename_ref -prefix_all vio_1_
write_checkpoint -noxdef vio_1.dcp
report_utilization -file vio_1_utilization_synth.rpt -pb vio_1_utilization_synth.pb
if { [catch {
  file copy -force Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.runs/vio_1_synth_1/vio_1.dcp Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1.dcp
  write_verilog -force -mode synth_stub Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_stub.v
  write_vhdl -force -mode synth_stub Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_stub.vhdl
  write_verilog -force -mode funcsim Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_funcsim.v
  write_vhdl -force -mode funcsim Z:/jtobin/vivado_projects/adc_fft_to_pc2/adc_fft_to_pc2.srcs/sources_1/ip/vio_1/vio_1_funcsim.vhdl
} _RESULT ] } { 
  send_msg_id runtcl-3 error "Unable to successfully create or copy supporting IP files."
  return -code error
}
