# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0.xci
# IP: The module: 'vio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0.xci
# IP: The module: 'vio_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /data1/cdaffron/git/ece551hw/final/top_level_project/top_level_project.srcs/sources_1/ip/vio_0/vio_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'vio_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
