# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1
set_property target_language VHDL [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
add_files C:/Users/cdaffron/git/ece551/lab1/551lab1.coe
add_files -quiet C:/Users/cdaffron/git/ece551/lab1/lab1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/cdaffron/git/ece551/lab1/lab1.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet C:/Users/cdaffron/git/ece551/lab1/lab1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp
set_property used_in_implementation false [get_files C:/Users/cdaffron/git/ece551/lab1/lab1.runs/clk_wiz_0_synth_1/clk_wiz_0.dcp]
add_files -quiet C:/Users/cdaffron/git/ece551/lab1/lab1.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp
set_property used_in_implementation false [get_files C:/Users/cdaffron/git/ece551/lab1/lab1.runs/c_counter_binary_0_synth_1/c_counter_binary_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/sources_1/imports/new/Hex2SSegDecoder.vhd
  C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/sources_1/new/debounce2.vhd
  C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/sources_1/imports/new/HexDigs2SSeg.vhd
  C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/sources_1/imports/new/CDiv.vhd
  C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/sources_1/new/top.vhd
}
read_xdc {{C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/constrs_1/imports/nexys 4 info/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/cdaffron/git/ece551/lab1/lab1.srcs/constrs_1/imports/nexys 4 info/Nexys4_Master.xdc}}]

read_xdc dont_buffer.xdc
set_property used_in_implementation false [get_files dont_buffer.xdc]
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/cdaffron/git/ece551/lab1/lab1.cache/wt [current_project]
set_property parent.project_dir C:/Users/cdaffron/git/ece551/lab1 [current_project]
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7a100tcsg324-1
write_checkpoint top.dcp
report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb
