set_property SRC_FILE_INFO {cfile:/data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc rfile:../../../bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:817 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[5]}]
set_property src_info {type:XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[2]}]
set_property src_info {type:XDC file:1 line:819 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[1]}]
set_property src_info {type:XDC file:1 line:820 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[4]}]
set_property src_info {type:XDC file:1 line:821 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[0]}]
set_property src_info {type:XDC file:1 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[3]}]
set_property src_info {type:XDC file:1 line:839 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets disp_draw_inst/n_0_inValid_reg]
set_property src_info {type:XDC file:1 line:922 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:923 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:924 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:925 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:926 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:927 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:928 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:929 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:930 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:931 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:932 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list debug_clk]]
set_property src_info {type:XDC file:1 line:933 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:934 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {FFT_data[0]} {FFT_data[1]} {FFT_data[2]} {FFT_data[3]} {FFT_data[4]} {FFT_data[5]} {FFT_data[6]} {FFT_data[7]} {FFT_data[8]} {FFT_data[9]} {FFT_data[10]} {FFT_data[11]} {FFT_data[12]} {FFT_data[13]} {FFT_data[14]} {FFT_data[15]} {FFT_data[16]} {FFT_data[17]} {FFT_data[18]} {FFT_data[19]} {FFT_data[20]} {FFT_data[21]} {FFT_data[22]} {FFT_data[23]} {FFT_data[24]} {FFT_data[25]} {FFT_data[26]} {FFT_data[27]} {FFT_data[28]} {FFT_data[29]} {FFT_data[30]} {FFT_data[31]}]]
set_property src_info {type:XDC file:1 line:935 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:936 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:937 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {FFT_addr[0]} {FFT_addr[1]} {FFT_addr[2]} {FFT_addr[3]} {FFT_addr[4]} {FFT_addr[5]} {FFT_addr[6]} {FFT_addr[7]} {FFT_addr[8]} {FFT_addr[9]}]]
set_property src_info {type:XDC file:1 line:938 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:939 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:940 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {disp_draw_inst/mag[0]} {disp_draw_inst/mag[1]} {disp_draw_inst/mag[2]} {disp_draw_inst/mag[3]} {disp_draw_inst/mag[4]} {disp_draw_inst/mag[5]} {disp_draw_inst/mag[6]} {disp_draw_inst/mag[7]} {disp_draw_inst/mag[8]} {disp_draw_inst/mag[9]} {disp_draw_inst/mag[10]} {disp_draw_inst/mag[11]} {disp_draw_inst/mag[12]} {disp_draw_inst/mag[13]} {disp_draw_inst/mag[14]} {disp_draw_inst/mag[15]} {disp_draw_inst/mag[16]}]]
set_property src_info {type:XDC file:1 line:941 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:942 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:943 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {disp_draw_inst/barNumOut[0]} {disp_draw_inst/barNumOut[1]} {disp_draw_inst/barNumOut[2]} {disp_draw_inst/barNumOut[3]} {disp_draw_inst/barNumOut[4]} {disp_draw_inst/barNumOut[5]}]]
set_property src_info {type:XDC file:1 line:944 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:945 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:946 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {disp_draw_inst/imagVal[0]} {disp_draw_inst/imagVal[1]} {disp_draw_inst/imagVal[2]} {disp_draw_inst/imagVal[3]} {disp_draw_inst/imagVal[4]} {disp_draw_inst/imagVal[5]} {disp_draw_inst/imagVal[6]} {disp_draw_inst/imagVal[7]} {disp_draw_inst/imagVal[8]} {disp_draw_inst/imagVal[9]} {disp_draw_inst/imagVal[10]} {disp_draw_inst/imagVal[11]} {disp_draw_inst/imagVal[12]} {disp_draw_inst/imagVal[13]} {disp_draw_inst/imagVal[14]} {disp_draw_inst/imagVal[15]}]]
set_property src_info {type:XDC file:1 line:947 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:948 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:949 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {disp_draw_inst/realVal[0]} {disp_draw_inst/realVal[1]} {disp_draw_inst/realVal[2]} {disp_draw_inst/realVal[3]} {disp_draw_inst/realVal[4]} {disp_draw_inst/realVal[5]} {disp_draw_inst/realVal[6]} {disp_draw_inst/realVal[7]} {disp_draw_inst/realVal[8]} {disp_draw_inst/realVal[9]} {disp_draw_inst/realVal[10]} {disp_draw_inst/realVal[11]} {disp_draw_inst/realVal[12]} {disp_draw_inst/realVal[13]} {disp_draw_inst/realVal[14]} {disp_draw_inst/realVal[15]}]]
set_property src_info {type:XDC file:1 line:950 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:951 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:952 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {disp_draw_inst/counter2[0]} {disp_draw_inst/counter2[1]} {disp_draw_inst/counter2[2]} {disp_draw_inst/counter2[3]} {disp_draw_inst/counter2[4]} {disp_draw_inst/counter2[5]} {disp_draw_inst/counter2[6]} {disp_draw_inst/counter2[7]}]]
set_property src_info {type:XDC file:1 line:953 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:954 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:955 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {disp_draw_inst/average[0]} {disp_draw_inst/average[1]} {disp_draw_inst/average[2]} {disp_draw_inst/average[3]} {disp_draw_inst/average[4]} {disp_draw_inst/average[5]} {disp_draw_inst/average[6]} {disp_draw_inst/average[7]} {disp_draw_inst/average[8]} {disp_draw_inst/average[9]} {disp_draw_inst/average[10]} {disp_draw_inst/average[11]} {disp_draw_inst/average[12]} {disp_draw_inst/average[13]} {disp_draw_inst/average[14]} {disp_draw_inst/average[15]}]]
set_property src_info {type:XDC file:1 line:956 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:957 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:958 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list disp_draw_inst/magValid]]
set_property src_info {type:XDC file:1 line:959 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:960 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:961 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[0]}]]
set_property src_info {type:XDC file:1 line:962 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:963 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:964 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[1]}]]
set_property src_info {type:XDC file:1 line:965 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:966 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:967 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[2]}]]
set_property src_info {type:XDC file:1 line:968 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:969 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:970 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[3]}]]
set_property src_info {type:XDC file:1 line:971 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:972 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:973 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[4]}]]
set_property src_info {type:XDC file:1 line:974 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:975 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:976 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[5]}]]
set_property src_info {type:XDC file:1 line:977 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:978 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:979 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list disp_draw_inst/n_0_inValid_reg]]
set_property src_info {type:XDC file:1 line:980 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:981 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:982 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list reset]]
set_property src_info {type:XDC file:1 line:983 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:984 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:986 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets debug_clk]
