set_property SRC_FILE_INFO {cfile:/data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc rfile:../../../bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:817 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[5]}]
set_property src_info {type:XDC file:1 line:818 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[2]}]
set_property src_info {type:XDC file:1 line:819 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[1]}]
set_property src_info {type:XDC file:1 line:820 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[4]}]
set_property src_info {type:XDC file:1 line:821 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[0]}]
set_property src_info {type:XDC file:1 line:822 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {disp_draw_inst/n_0_barNumIn_reg[3]}]
set_property src_info {type:XDC file:1 line:839 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets disp_draw_inst/n_0_inValid_reg]
set_property src_info {type:XDC file:1 line:965 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[0]}]]
set_property src_info {type:XDC file:1 line:966 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[1]}]]
set_property src_info {type:XDC file:1 line:967 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[2]}]]
set_property src_info {type:XDC file:1 line:968 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[3]}]]
set_property src_info {type:XDC file:1 line:969 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[4]}]]
set_property src_info {type:XDC file:1 line:970 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list {disp_draw_inst/n_0_barNumIn_reg[5]}]]
set_property src_info {type:XDC file:1 line:971 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list disp_draw_inst/n_0_inValid_reg]]
set_property src_info {type:XDC file:1 line:972 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list n_53_fft_fsm]]
set_property src_info {type:XDC file:1 line:973 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list n_54_fft_fsm]]
set_property src_info {type:XDC file:1 line:974 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list n_55_fft_fsm]]
set_property src_info {type:XDC file:1 line:975 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list n_56_fft_fsm]]
set_property src_info {type:XDC file:1 line:976 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list n_57_fft_fsm]]
set_property src_info {type:XDC file:1 line:977 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list n_58_fft_fsm]]
set_property src_info {type:XDC file:1 line:978 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list n_59_fft_fsm]]
set_property src_info {type:XDC file:1 line:979 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list n_60_fft_fsm]]
set_property src_info {type:XDC file:1 line:980 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list n_61_fft_fsm]]
set_property src_info {type:XDC file:1 line:981 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list n_62_fft_fsm]]
set_property src_info {type:XDC file:1 line:983 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tvalid]
set_property src_info {type:XDC file:1 line:984 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tlast]
set_property src_info {type:XDC file:1 line:985 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tready]
set_property src_info {type:XDC file:1 line:986 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/event_frame_started]
set_property src_info {type:XDC file:1 line:987 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:988 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:989 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:990 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:991 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:992 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:993 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:994 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:995 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:996 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:997 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list debug_clk]]
set_property src_info {type:XDC file:1 line:998 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:999 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {m_axis_data_tdata[0]} {m_axis_data_tdata[1]} {m_axis_data_tdata[2]} {m_axis_data_tdata[3]} {m_axis_data_tdata[4]} {m_axis_data_tdata[5]} {m_axis_data_tdata[6]} {m_axis_data_tdata[7]} {m_axis_data_tdata[8]} {m_axis_data_tdata[9]} {m_axis_data_tdata[10]} {m_axis_data_tdata[11]} {m_axis_data_tdata[12]} {m_axis_data_tdata[13]} {m_axis_data_tdata[14]} {m_axis_data_tdata[15]} {m_axis_data_tdata[16]} {m_axis_data_tdata[17]} {m_axis_data_tdata[18]} {m_axis_data_tdata[19]} {m_axis_data_tdata[20]} {m_axis_data_tdata[21]} {m_axis_data_tdata[22]} {m_axis_data_tdata[23]} {m_axis_data_tdata[24]} {m_axis_data_tdata[25]} {m_axis_data_tdata[26]} {m_axis_data_tdata[27]} {m_axis_data_tdata[28]} {m_axis_data_tdata[29]} {m_axis_data_tdata[30]} {m_axis_data_tdata[31]}]]
set_property src_info {type:XDC file:1 line:1000 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1001 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:1002 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {disp_draw_inst/barNumOut[0]} {disp_draw_inst/barNumOut[1]} {disp_draw_inst/barNumOut[2]} {disp_draw_inst/barNumOut[3]} {disp_draw_inst/barNumOut[4]} {disp_draw_inst/barNumOut[5]}]]
set_property src_info {type:XDC file:1 line:1003 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1004 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:1005 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {disp_draw_inst/average[0]} {disp_draw_inst/average[1]} {disp_draw_inst/average[2]} {disp_draw_inst/average[3]} {disp_draw_inst/average[4]} {disp_draw_inst/average[5]} {disp_draw_inst/average[6]} {disp_draw_inst/average[7]} {disp_draw_inst/average[8]} {disp_draw_inst/average[9]} {disp_draw_inst/average[10]} {disp_draw_inst/average[11]} {disp_draw_inst/average[12]} {disp_draw_inst/average[13]} {disp_draw_inst/average[14]} {disp_draw_inst/average[15]}]]
set_property src_info {type:XDC file:1 line:1006 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1007 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:1008 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {disp_draw_inst/counter2[0]} {disp_draw_inst/counter2[1]} {disp_draw_inst/counter2[2]} {disp_draw_inst/counter2[3]} {disp_draw_inst/counter2[4]} {disp_draw_inst/counter2[5]} {disp_draw_inst/counter2[6]} {disp_draw_inst/counter2[7]}]]
set_property src_info {type:XDC file:1 line:1009 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1010 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:1011 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {FFT_data[0]} {FFT_data[1]} {FFT_data[2]} {FFT_data[3]} {FFT_data[4]} {FFT_data[5]} {FFT_data[6]} {FFT_data[7]} {FFT_data[8]} {FFT_data[9]} {FFT_data[10]} {FFT_data[11]} {FFT_data[12]} {FFT_data[13]} {FFT_data[14]} {FFT_data[15]} {FFT_data[16]} {FFT_data[17]} {FFT_data[18]} {FFT_data[19]} {FFT_data[20]} {FFT_data[21]} {FFT_data[22]} {FFT_data[23]} {FFT_data[24]} {FFT_data[25]} {FFT_data[26]} {FFT_data[27]} {FFT_data[28]} {FFT_data[29]} {FFT_data[30]} {FFT_data[31]}]]
set_property src_info {type:XDC file:1 line:1012 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1013 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:1014 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {FFT_addr[0]} {FFT_addr[1]} {FFT_addr[2]} {FFT_addr[3]} {FFT_addr[4]} {FFT_addr[5]} {FFT_addr[6]} {FFT_addr[7]} {FFT_addr[8]} {FFT_addr[9]}]]
set_property src_info {type:XDC file:1 line:1015 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1016 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:1017 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {disp_draw_inst/realVal[0]} {disp_draw_inst/realVal[1]} {disp_draw_inst/realVal[2]} {disp_draw_inst/realVal[3]} {disp_draw_inst/realVal[4]} {disp_draw_inst/realVal[5]} {disp_draw_inst/realVal[6]} {disp_draw_inst/realVal[7]} {disp_draw_inst/realVal[8]} {disp_draw_inst/realVal[9]} {disp_draw_inst/realVal[10]} {disp_draw_inst/realVal[11]} {disp_draw_inst/realVal[12]} {disp_draw_inst/realVal[13]} {disp_draw_inst/realVal[14]} {disp_draw_inst/realVal[15]}]]
set_property src_info {type:XDC file:1 line:1018 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1019 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 17 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:1020 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {disp_draw_inst/mag[0]} {disp_draw_inst/mag[1]} {disp_draw_inst/mag[2]} {disp_draw_inst/mag[3]} {disp_draw_inst/mag[4]} {disp_draw_inst/mag[5]} {disp_draw_inst/mag[6]} {disp_draw_inst/mag[7]} {disp_draw_inst/mag[8]} {disp_draw_inst/mag[9]} {disp_draw_inst/mag[10]} {disp_draw_inst/mag[11]} {disp_draw_inst/mag[12]} {disp_draw_inst/mag[13]} {disp_draw_inst/mag[14]} {disp_draw_inst/mag[15]} {disp_draw_inst/mag[16]}]]
set_property src_info {type:XDC file:1 line:1021 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1022 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 16 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:1023 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {disp_draw_inst/imagVal[0]} {disp_draw_inst/imagVal[1]} {disp_draw_inst/imagVal[2]} {disp_draw_inst/imagVal[3]} {disp_draw_inst/imagVal[4]} {disp_draw_inst/imagVal[5]} {disp_draw_inst/imagVal[6]} {disp_draw_inst/imagVal[7]} {disp_draw_inst/imagVal[8]} {disp_draw_inst/imagVal[9]} {disp_draw_inst/imagVal[10]} {disp_draw_inst/imagVal[11]} {disp_draw_inst/imagVal[12]} {disp_draw_inst/imagVal[13]} {disp_draw_inst/imagVal[14]} {disp_draw_inst/imagVal[15]}]]
set_property src_info {type:XDC file:1 line:1024 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1025 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:1026 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list fft/event_frame_started]]
set_property src_info {type:XDC file:1 line:1027 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1028 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:1029 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list fft/m_axis_data_tlast]]
set_property src_info {type:XDC file:1 line:1030 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1031 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:1032 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list fft/m_axis_data_tready]]
set_property src_info {type:XDC file:1 line:1033 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1034 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:1035 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list fft/m_axis_data_tvalid]]
set_property src_info {type:XDC file:1 line:1036 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1037 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:1038 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list disp_draw_inst/magValid]]
set_property src_info {type:XDC file:1 line:1039 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1040 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:1041 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list n_106_fft_fsm]]
set_property src_info {type:XDC file:1 line:1042 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1043 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:1044 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list n_107_fft_fsm]]
set_property src_info {type:XDC file:1 line:1045 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1046 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:1047 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list n_108_fft_fsm]]
set_property src_info {type:XDC file:1 line:1048 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1049 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:1050 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list n_109_fft_fsm]]
set_property src_info {type:XDC file:1 line:1051 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1052 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:1053 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list n_110_fft_fsm]]
set_property src_info {type:XDC file:1 line:1054 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1055 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:1056 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list n_111_fft_fsm]]
set_property src_info {type:XDC file:1 line:1057 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1058 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:1059 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list n_112_fft_fsm]]
set_property src_info {type:XDC file:1 line:1060 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1061 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:1062 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list n_113_fft_fsm]]
set_property src_info {type:XDC file:1 line:1063 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1064 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:1065 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list n_114_fft_fsm]]
set_property src_info {type:XDC file:1 line:1066 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1067 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:1068 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list n_115_fft_fsm]]
set_property src_info {type:XDC file:1 line:1069 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1070 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:1071 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list n_116_fft_fsm]]
set_property src_info {type:XDC file:1 line:1072 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1073 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:1074 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list n_117_fft_fsm]]
set_property src_info {type:XDC file:1 line:1075 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1076 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:1077 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list n_118_fft_fsm]]
set_property src_info {type:XDC file:1 line:1078 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:1079 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:1080 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list reset]]
set_property src_info {type:XDC file:1 line:1081 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1082 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1083 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:1084 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets debug_clk]
