set_property SRC_FILE_INFO {cfile:/data1/cdaffron/git/ece551hw/final/chris/bars_to_seg_disp/bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc rfile:../../../bars_to_seg_disp.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:947 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tvalid]
set_property src_info {type:XDC file:1 line:948 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tlast]
set_property src_info {type:XDC file:1 line:949 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/m_axis_data_tready]
set_property src_info {type:XDC file:1 line:950 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets fft/event_frame_started]
