set_property SRC_FILE_INFO {cfile:/data1/cdaffron/git/ece551hw/final/john/top_level2_2014.2/top_level2_2014.2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc rfile:../../../top_level2_2014.2.srcs/constrs_1/imports/lab2/Nexys4_Master.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:871 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:872 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:873 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:874 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:875 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:876 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:877 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:878 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:879 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:880 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:881 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list debug_clk]]
set_property src_info {type:XDC file:1 line:882 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:883 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {vga_comp/vga_disp/vcount[0]} {vga_comp/vga_disp/vcount[1]} {vga_comp/vga_disp/vcount[2]} {vga_comp/vga_disp/vcount[3]} {vga_comp/vga_disp/vcount[4]} {vga_comp/vga_disp/vcount[5]} {vga_comp/vga_disp/vcount[6]} {vga_comp/vga_disp/vcount[7]} {vga_comp/vga_disp/vcount[8]} {vga_comp/vga_disp/vcount[9]} {vga_comp/vga_disp/vcount[10]}]]
set_property src_info {type:XDC file:1 line:884 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:885 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:886 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {vga_comp/vga_disp/relY[0]} {vga_comp/vga_disp/relY[1]} {vga_comp/vga_disp/relY[2]} {vga_comp/vga_disp/relY[3]} {vga_comp/vga_disp/relY[4]} {vga_comp/vga_disp/relY[5]} {vga_comp/vga_disp/relY[6]} {vga_comp/vga_disp/relY[7]} {vga_comp/vga_disp/relY[8]} {vga_comp/vga_disp/relY[9]}]]
set_property src_info {type:XDC file:1 line:887 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:888 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 10 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:889 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {vga_comp/vga_disp/relX[0]} {vga_comp/vga_disp/relX[1]} {vga_comp/vga_disp/relX[2]} {vga_comp/vga_disp/relX[3]} {vga_comp/vga_disp/relX[4]} {vga_comp/vga_disp/relX[5]} {vga_comp/vga_disp/relX[6]} {vga_comp/vga_disp/relX[7]} {vga_comp/vga_disp/relX[8]} {vga_comp/vga_disp/relX[9]}]]
set_property src_info {type:XDC file:1 line:890 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:891 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 11 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:892 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {vga_comp/vga_disp/hcount[0]} {vga_comp/vga_disp/hcount[1]} {vga_comp/vga_disp/hcount[2]} {vga_comp/vga_disp/hcount[3]} {vga_comp/vga_disp/hcount[4]} {vga_comp/vga_disp/hcount[5]} {vga_comp/vga_disp/hcount[6]} {vga_comp/vga_disp/hcount[7]} {vga_comp/vga_disp/hcount[8]} {vga_comp/vga_disp/hcount[9]} {vga_comp/vga_disp/hcount[10]}]]
set_property src_info {type:XDC file:1 line:893 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:894 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:895 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {vga_comp/vga_disp/curBarH[0]} {vga_comp/vga_disp/curBarH[1]} {vga_comp/vga_disp/curBarH[2]} {vga_comp/vga_disp/curBarH[3]} {vga_comp/vga_disp/curBarH[4]} {vga_comp/vga_disp/curBarH[5]} {vga_comp/vga_disp/curBarH[6]} {vga_comp/vga_disp/curBarH[7]}]]
set_property src_info {type:XDC file:1 line:896 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:897 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 9 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:898 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {vga_comp/vga_disp/actY[0]} {vga_comp/vga_disp/actY[2]} {vga_comp/vga_disp/actY[3]} {vga_comp/vga_disp/actY[4]} {vga_comp/vga_disp/actY[5]} {vga_comp/vga_disp/actY[6]} {vga_comp/vga_disp/actY[7]} {vga_comp/vga_disp/actY[8]} {vga_comp/vga_disp/actY[9]}]]
set_property src_info {type:XDC file:1 line:899 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:900 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 6 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:901 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {vga_comp/vga_disp/actX[4]} {vga_comp/vga_disp/actX[5]} {vga_comp/vga_disp/actX[6]} {vga_comp/vga_disp/actX[7]} {vga_comp/vga_disp/actX[8]} {vga_comp/vga_disp/actX[9]}]]
set_property src_info {type:XDC file:1 line:902 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:903 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:904 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {disp_draw_inst/counter2[0]} {disp_draw_inst/counter2[1]} {disp_draw_inst/counter2[2]} {disp_draw_inst/counter2[3]} {disp_draw_inst/counter2[4]} {disp_draw_inst/counter2[5]} {disp_draw_inst/counter2[6]} {disp_draw_inst/counter2[7]}]]
set_property src_info {type:XDC file:1 line:905 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:906 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:907 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list reset]]
set_property src_info {type:XDC file:1 line:908 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:909 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:910 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:911 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets xlnx_opt_]
